import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
  {
    id: "tVHgkhHHquI",
    video_title: "Video 1",
    video_description: "",
    tags: [],
    cover_image: "tVHgkhHHquI",
    publish_date: "2024-03-25",
    client_name: "Ahmad Dawar",
    client_image: "/ahmadpic.jpg",
    client_feedback: "Loved the editing and the storytelling in this vlog!",
    video_link: "https://www.youtube.com/watch?v=tVHgkhHHquI",
    project_images: [],
    category: ["Vlog", "Talking Head"],
    duration: "12:35",
    software_used: ["Adobe Premiere Pro", "After Effects"],
  },
  {
    id: "mInNL2eyxxo",
    video_title: "Video 2",
    video_description: "",
    tags: [],
    cover_image: "mInNL2eyxxo",
    publish_date: "2024-03-20",
    client_name: "Ahmad Dawar",
    client_image: "/ahmadpic.jpg",
    client_feedback: "",
    video_link: "https://www.youtube.com/watch?v=mInNL2eyxxo",
    project_images: [],
    category: ["Vlog", "Cinematic"],
    duration: "10:18",
    software_used: ["Adobe Premiere Pro"],
  },
  {
    id: "evzYelBrpl8",
    video_title: "Video 3",
    video_description: "",
    tags: [],
    cover_image: "evzYelBrpl8",
    publish_date: "2024-03-15",
    client_name: "Ahmad Dawar",
    client_image: "/ahmadpic.jpg",
    client_feedback: "",
    video_link: "https://www.youtube.com/watch?v=evzYelBrpl8",
    project_images: [],
    category: ["Vlog", "Explainer"],
    duration: "8:45",
    software_used: ["Davinci Resolve"],
  },
  {
    id: "WlyCWhugOag",
    video_title: "Short 1",
    video_description: "",
    tags: [],
    cover_image: "WlyCWhugOag",
    publish_date: "2024-03-22",
    client_name: "Ahmad Dawar",
    client_image: "/ahmadpic.jpg",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/WlyCWhugOag",
    project_images: [],
    category: ["Shorts", "Promo"],
    duration: "0:58",
    software_used: ["CapCut", "After Effects"],
  },
  {
    id: "S0wEqI6vPaM",
    video_title: "Short 2",
    video_description: "",
    tags: [],
    cover_image: "S0wEqI6vPaM",
    publish_date: "2024-03-18",
    client_name: "Ahmad Dawar",
    client_image: "/ahmadpic.jpg",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/S0wEqI6vPaM",
    project_images: [],
    category: ["Shorts", "Comedy"],
    duration: "0:45",
    software_used: ["CapCut"],
  },
  {
    id: "SW8eUrdYpXk",
    video_title: "Short 3",
    video_description: "",
    tags: [],
    cover_image: "SW8eUrdYpXk",
    publish_date: "2024-03-12",
    client_name: "Ahmad Dawar",
    client_image: "/ahmadpic.jpg",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/SW8eUrdYpXk",
    project_images: [],
    category: ["Shorts", "Cinematic"],
    duration: "0:52",
    software_used: ["CapCut", "After Effects"],
  },
];
